import Link from "next/link";
import "./globals.css";
import { AiFillHome } from "react-icons/ai";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Link href="/">
          <div className="border p-4 w-16 rounded-sm">
            <AiFillHome className="text-3xl text-linkedin" />
          </div>
        </Link>
        {children}
      </body>
    </html>
  );
}
